.PHONY: run-server
run-server:
	python3 manage.py runserver

.PHONY: create-tables
create-tables:
	python3 manage.py create_tables

.PHONY: initial-data
initial-data:
	python3 manage.py initial_data

.PHONY: collect-static
collect-static:
	python3 manage.py collectstatic --noinput